-- Migration v7 to v8: SQLite column rename workaround
-- For SQLite, we'll rely on the application's ensureParticipantsTableIntegrity function
-- to handle column renaming, as SQLite migrations are more complex for column operations